### PR TITLE
[WIP] internationalization

### LINKED ISSUE #80: Internationalize the plugin
Hi. 
Thanks for the great work.
Currently the plugin doesn't follows the WP guidelines for intenationalization https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/
so it can't be translated in other languages. 

Bests Lena

### PR DESCRIPTION
**Pull request by zhaofeng-shu33**
Fixes #80

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin
```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Comment by vestigialcode** [comment]
So how its used transifex?

**Comment by zhaofeng-shu33** [comment]
> transifex

wordpress transifex is commercial software and is unsuitable to translate open source wp plugin, I think

**Comment by ahmadbilaldev** [comment]
If you want, you can utilize tools like [WPGulp](https://github.com/ahmadawais/WPGulp). Also, a good feature to propose will be GitHub Actions setup for automated generation of these .pot files.

**Comment by ahmadbilaldev** [comment]
I will test your changes and report back.

**Comment by zhaofeng-shu33** [comment]
> Thank you for your efforts. I will test your changes and report back.

You can add your mother tongue to check further.

**Comment by Rajesh-Royal** [comment]
> > transifex
> 
> wordpress transifex is commercial software and is unsuitable to translate open source wp plugin, I think

read their Open source guidelines - https://docs.transifex.com/projects/open-source-project
you can contribute to the project here - https://www.transifex.com/rtu-university/creative-common-internationalization/

**Comment by zhaofeng-shu33** [comment]
I wonder whether `transifex` wordpress plugin is targeting for website visitors or website admin.

**Comment by Rajesh-Royal** [comment]
> I wonder whether `transifex` wordpress plugin is targeting for website visitors or website admin.

both the visitors and the site admins.

**Comment by Rajesh-Royal** [comment]
> If you want, you can utilize tools like [WPGulp](https://github.com/ahmadawais/WPGulp). Also, a good feature to propose will be GitHub Actions setup for automated generation of these .pot files.

Warning message `Write protected: Creating this file requires permission. Click "Connect" to authenticate with the server.` when we try to use default .po file in Loco translator

**Comment by zhaofeng-shu33** [comment]
In "transifex" way, I think we do not need to put each language into `.mo` file. Maybe it is saved into database by the plugin.

**Comment by Rajesh-Royal** [comment]
> In "transifex" way, I think we do not need to put each language into `.mo` file. Maybe it is saved into database by the plugin.

When you work with transifex wp plugin you have to create a live project and connect it with wp by an api key. There will be nothing to save in db. Everything will be saved on transifix dashboard. Or to easy the process you can use loco translator.

**Comment by zhaofeng-shu33** [comment]
ok

**Comment by Rajesh-Royal** [comment]
> Good work! thanks for your contribution
> I understand you add the zh_CN files for test purpose, but I think we shouldn't add incomplete translations on plugin releases. Can you remove it from the PR please?

@hugosolar can contributors have access to default.po file so they can translate it into their language. It's protected.

**Comment by zhaofeng-shu33** [comment]
> Good work! thanks for your contribution
> I understand you add the zh_CN files for test purpose, but I think we shouldn't add incomplete translations on plugin releases. Can you remove it from the PR please?

Can I make complete translation from the `default.po`?

**Comment by hugosolar** [comment]
I think default.po is outdated... @Rajesh-Royal what do you mean by saying is protected?

**Comment by zhaofeng-shu33** [comment]
I can regenerate from the source code.

**Comment by Rajesh-Royal** [comment]
> I think default.po is outdated... @Rajesh-Royal what do you mean by saying is protected?

here
`Write protected: Creating this file requires permission. Click "Connect" to authenticate with the server.`

image

**Comment by hugosolar** [comment]
@zhaofeng-shu33  you check [WP-CLI command](https://developer.wordpress.org/cli/commands/i18n/make-pot/) to do that

**Comment by brylie** [comment]
@all-contributors please add @zhaofeng-shu33 for translation

**Pull request merged**
