### PR TITLE
Javascript/NPM fix

### LINKED ISSUE #230: [Bug] Fix JavaScript/NPM (replace cgb-scripts)
## Description

1. `npm install` fails.
2. https://github.com/creativecommons/wp-plugin-creativecommons/blob/c3e7ab96614e4d736a15fc8a378606262b56f327/package.json#L12-L14
   - [cgb-scripts - npm](https://www.npmjs.com/package/cgb-scripts) indicates this packages hasn't been supported for 4 years!
     > Last Publish 2020-07-11
     - The parent project, [ahmadawais/create-guten-block](https://github.com/ahmadawais/create-guten-block), was archived in 2022:
       > This repository has been archived by the owner on Oct 10, 2022. It is now read-only.
3. [Consider officially deprecating CGB · Issue #298 · ahmadawais/create-guten-block](https://github.com/ahmadawais/create-guten-block/issues/298)
   > I do question though, now that WordPress has an official [@wordpress/create-block](https://www.npmjs.com/package/@wordpress/create-block) package for scaffolding blocks, **should CGB be officially deprecated?** 
4. https://github.com/ahmadawais/create-guten-block/issues/298#issuecomment-1081830658
    > I'm looking to remove this library from our projects (`npm run build` doesn't run on Node 16 because of an old SASS dependency). 
   - [node - Official Image | Docker Hub](https://hub.docker.com/_/node/) no longer lists versions older than 18
   - #231 

## Expectation
Refactor to use [@wordpress/create-block - npm](https://www.npmjs.com/package/@wordpress/create-block)?

## Additional context
😭 

## Resolution

- 🙅🏻  ~~I would be interested in resolving this bug.~~

### PR DESCRIPTION
**Pull request by RonaldRonnie**
- Fixes #230

scripts configuration

- Updated start script to use relative path
 for nodemon
- Replaced cgb-scripts to resolve NPM
 configuration errors
- Ensured compatibility with the plugin
 development environment

### CODE REVIEW

**Comment by RonaldRonnie** [comment]
here when **docker compose down and
docker compose up --build** are used , This help 
Screenshot from 2024-10-17 17-30-30
containers to ensure everything is up-to-date. and thus the localhost:8080 can be accessed
image

**Comment by possumbilities** [comment]
Hi @RonaldRonnie, thanks for this contribution. Resolving this Issue would likely first require resolving the connected issue of: 
- #211 

There is a lot of work here, and it would be helpful if your PR description more thoroughly documented all the changes you've made within this PR and whether or not it satisfies #211 or just #230 alone.

I've also moved #230 to https://github.com/creativecommons/wp-plugin-creativecommons/labels/%F0%9F%9A%A7%20status%3A%20blocked just because it seems we're approaching the territory where we likely need to resolve #211 rather than continue with any form of `create-guten-block`

**Comment by RonaldRonnie** [comment]
Okay please, am happy to contribute

**Comment by possumbilities** [comment]
Hi again @RonaldRonnie Could you please fill out the Issue template, rather than deleting it, and include details related to my previous comment?

**Comment by RonaldRonnie** [comment]
So should open up another issue that will be fulfilled by my PR? because initially there were outdated modules and so i had to change to the one that supports the server to start and for that case one can start docker

**Comment by possumbilities** [comment]
Hi @RonaldRonnie I'm closing this since it does not utilize the PR template, and seems out of scope with resolving the original now blocked Issued. 

Please feel free to open future PRs following the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/)

**Comment by RonaldRonnie** [comment]
Thank you @possumbilities for giving me this chance let me work on the issue

**Pull request closed without merging**
